### ISSUE TITLE
TODO for next releases

### ISSUE THREAD

**Issue by Lotes** [Lotes/keynote-archives#4]
Publishing
* [x] fix publish files and main file in package.json
* [x] add index.ts in source root

Research and documentation
* [x] [Diagram](https://www.planttext.com/?text=NP5D2y8m38Rl_HMnnu43hqDa8WZYOO87p_k8EDtQqWzXue-tQ-qwlJJ9cxnF0isLBgKsVKSM-eOzmhEjPCaqkROTmX47nZL2gO2c3noeb_VsyLbXJJAMXyis5hkROG-VdbafnE25mAGh2ibo2JIX7ZW-i7vRALAZ5j3VwEoJVyx_ttsINFFAN8lgZhKcir77i0GNlIFg0Vrd3zUdwSPT3HaOzch5TDVOcE_8eC7QiUVgE1NwXjMy5nAL8h7vkpO39RfM-qAH75bZl-m3)
* [ ] find out how to read the remaining archives
  * [ ] add own file format description after found out
* [x] #7

Updating meta files
* [ ] #8
  * protobuf files
  * mapping

Demo
* [x] #6

Tests
* [ ] add E2E tests by processing some chosen files

Improvements
* [x] fix assertBounds
* [x] decoder: add archive info to IWA file
* [x] #5
* [x] rename serialize to toJsonString
